<?php

/**
* Implements hook_entity_view_alter().
*/
function unset_html_head_link_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  // Cheking view_mode for node.
  if ($build['#view_mode'] === 'full' && $entity Instanceof \Drupal\node\NodeInterface) {
    // Cheking html_head_link on attached tags in head.
    if (!isset($build['#attached']['html_head_link'])) return;
    // Array to unset.
    $unset_html_head_link = [
      'delete-form',
      'edit-form',
      'version-history',
      'revision'
    ];
    // Unset loop.
    foreach ($build['#attached']['html_head_link'] as $key => $value) {
      if (isset($value[0]['rel']) && in_array($value[0]['rel'], $unset_html_head_link)) unset($build['#attached']['html_head_link'][$key]);
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function unset_html_head_link_page_attachments_alter(array &$attachments) {
  // Array to unset.
  $unset_html_head_link = [
    'delete-form',
    'edit-form',
    'version-history',
    'revision'
  ];
  // Unset loop.
  foreach ($attachments['#attached']['html_head_link'] as $key => $value) {
    if (isset($value[0]['rel']) && in_array($value[0]['rel'], $unset_html_head_link)) unset($attachments['#attached']['html_head_link'][$key]);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function unset_html_head_link_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'page_attachments_alter') {
    $group = $implementations['unset_html_head_link'];
    unset($implementations['unset_html_head_link']);
    $implementations['unset_html_head_link'] = $group;
  }
}
